// @ts-nocheck
/* auto-generated by NAPI-RS. To modify the header, go to ./src/custom-types.d.ts */
/* eslint-disable */

// NAPI-RS does not properly generates types definitions for objects,
// with manual definitions of (To/From)NapiValue. For this reason,
// we manually define those types, in order to use them in the JS part of the code.

/**
 * Represents a CQL column type, including complex/nested types.
 * This type represents the guarantees, that the value returned from Rust promises to have.
 */
export type ComplexType =
  | { baseType: Exclude<CqlType, CqlType.List | CqlType.Set | CqlType.Map | CqlType.Vector | CqlType.Udt | CqlType.Tuple> }
  | { baseType: CqlType.List | CqlType.Set; frozen: boolean; subtype1: ComplexType }
  | { baseType: CqlType.Map; frozen: boolean; subtype1: ComplexType; subtype2: ComplexType }
  | { baseType: CqlType.Vector; subtype1: ComplexType; dimensions: number }
  | { baseType: CqlType.Udt; frozen: boolean; name: string; keyspace: string; udt_types: ComplexType[]; udt_name: string[] }
  | { baseType: CqlType.Tuple; subtypes: ComplexType[] }

/**
 * Result of a paged query.
 * Serialized as a 2-element tuple: [pagingState, result].
 * - pagingState is null when there are no more pages.
 */
export type PagingResult = [PagingStateWrapper | null, QueryResultWrapper]

/**
 * Result of a paged query that can be continued via a QueryExecutor.
 * Serialized as a 3-element tuple: [pagingState, result, executor].
 * - pagingState is null when there are no more pages.
 * 
 * This type can also be used to represent an unpaged query result, to allow for better code reuse.
 * This kind of result can be represented by setting pagingState and executor to undefined.
 */
export type PagingResultWithExecutor = [PagingStateWrapper | null, QueryResultWrapper, QueryExecutor]
  | [undefined, QueryResultWrapper, undefined]


/**
 * A pre-encoded CQL value passed to query parameters.
 * Null represents no value, and undefined represents unset value.
 */
export type EncodedValuesWrapper = Uint8Array | null | undefined

// ---------------------------------------------------------------------------
// Types for objects produced by define_rust_to_js_convertible_object.
// These are plain JS objects returned from Rust to JS
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Types for objects produced by define_js_to_rust_convertible_object.
// These are plain JS objects passed from JS into Rust (all fields optional).
// ---------------------------------------------------------------------------

/** TLS/SSL configuration passed to SessionOptions.sslOptions. */
export interface SslOptions {
  ca?: Array<string>
  cert?: string
  sigalgs?: string
  ciphers?: string
  ecdhCurve?: string
  honorCipherOrder?: boolean
  key?: string
  maxVersion?: TlsVersion
  minVersion?: TlsVersion
  passphrase?: string
  pfx?: string
  secureOptions?: bigint
  rejectUnauthorized?: boolean
}

/** Load-balancing configuration passed to SessionOptions.loadBalancingConfig. */
export interface LoadBalancingConfig {
  preferDatacenter?: string
  preferRack?: string
  tokenAware?: boolean
  permitDcFailover?: boolean
  enableShufflingReplicas?: boolean
  allowList?: Array<string>
}

/** Options for creating a new session via SessionWrapper.createSession. */
export interface SessionOptions {
  connectPoints?: Array<string>
  keyspace?: string
  applicationName?: string
  applicationVersion?: string
  clientId?: string
  credentialsUsername?: string
  credentialsPassword?: string
  cacheSize?: number
  sslOptions?: SslOptions
  loadBalancingConfig?: LoadBalancingConfig
  retryPolicy?: RetryPolicyKind
}

/** Per-query options passed to QueryOptionsWrapper. */
export interface QueryOptionsObj {
  autoPage?: boolean
  captureStackTrace?: boolean
  consistency?: number
  counter?: boolean
  fetchSize?: number
  isIdempotent?: boolean
  keyspace?: string
  logged?: boolean
  prepare?: boolean
  readTimeout?: number
  routingIndexes?: Array<number>
  routingNames?: Array<string>
  serialConsistency?: number
  timestamp?: bigint
  traceQuery?: boolean
}


///////////////////////////////////////////////
/* END OF CUSTOM TYPE DEFINITIONS.           */
/* All values below are generated by NAPI-RS */
///////////////////////////////////////////////
